name = "Create & Co"
author = "Brizzy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f06a98781f23e22fb8407498bbe7eba662f633c17f4a3775a9b5801c62d7d08"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.216"
